//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDocumentCardDraft
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://inform.gazprom.ru/I/IUSPT2_SED/eDocumentCardDraft", ConfigurationName="ServiceReference1.eDocumentCardDraftOut")]
    public interface eDocumentCardDraftOut
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://sap.com/xi/WebService/soap1.1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task ExportAsyncAsync(EDocumentCardDraft.ExportAsync request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inform.gazprom.ru/C/IUSPT2/eDocumentCardDraft")]
    public partial class eDocumentCardDraft
    {
        
        private string oUTSIDE_NUMBERField;
        
        private string zCNTRLEGALFORMField;
        
        private string zCNTRCATField;
        
        private string zCNTRTYPEField;
        
        private string zCNTRDATEField;
        
        private string zPARTNERField;
        
        private string zPAYRCPField;
        
        private string zCNTRDSCRPField;
        
        private string zCNTRSUMField;
        
        private string zPARENTCARDNUField;
        
        private string zGSBERField;
        
        private string zEXECUTORField;
        
        private string pARTICIPANT_CNTRField;
        
        private string gSBER_REGField;
        
        private string tYPE_CNTRField;
        
        private string fINANCIAL_SIGNField;
        
        private string zSIGNDATEField;
        
        private string zSTARTDATEField;
        
        private string zENDDATEField;
        
        private string zENDDATEPAYField;
        
        private string zFISTLField;
        
        private string gSBER_DCCField;
        
        private string zTERMField;
        
        private string hBKIDField;
        
        private string sIGNED_BYField;
        
        private string sUM_NDSField;
        
        private string zCNTRSUMADDField;
        
        private string zCNTRNDSADDField;
        
        private string nOT_SUM_CNTRField;
        
        private string zFIPOSField;
        
        private string zBUSINESSPARTNERField;
        
        private string zPAYRCP_FPField;
        
        private string zFISTL_ITEMField;
        
        private string dEPARTM_CONTROLField;
        
        private string fINCODEField;
        
        private string zLSCHField;
        
        private string zSTARTDATE_FPField;
        
        private string zENDDATE_FPField;
        
        private string oKPD2Field;
        
        private string bANKGARANTField;
        
        private string zCOMMENTARYField;
        
        private string tEMPLATEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OUTSIDE_NUMBER
        {
            get
            {
                return this.oUTSIDE_NUMBERField;
            }
            set
            {
                this.oUTSIDE_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZCNTRLEGALFORM
        {
            get
            {
                return this.zCNTRLEGALFORMField;
            }
            set
            {
                this.zCNTRLEGALFORMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZCNTRCAT
        {
            get
            {
                return this.zCNTRCATField;
            }
            set
            {
                this.zCNTRCATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ZCNTRTYPE
        {
            get
            {
                return this.zCNTRTYPEField;
            }
            set
            {
                this.zCNTRTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ZCNTRDATE
        {
            get
            {
                return this.zCNTRDATEField;
            }
            set
            {
                this.zCNTRDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ZPARTNER
        {
            get
            {
                return this.zPARTNERField;
            }
            set
            {
                this.zPARTNERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ZPAYRCP
        {
            get
            {
                return this.zPAYRCPField;
            }
            set
            {
                this.zPAYRCPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ZCNTRDSCRP
        {
            get
            {
                return this.zCNTRDSCRPField;
            }
            set
            {
                this.zCNTRDSCRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ZCNTRSUM
        {
            get
            {
                return this.zCNTRSUMField;
            }
            set
            {
                this.zCNTRSUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ZPARENTCARDNU
        {
            get
            {
                return this.zPARENTCARDNUField;
            }
            set
            {
                this.zPARENTCARDNUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ZGSBER
        {
            get
            {
                return this.zGSBERField;
            }
            set
            {
                this.zGSBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ZEXECUTOR
        {
            get
            {
                return this.zEXECUTORField;
            }
            set
            {
                this.zEXECUTORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string PARTICIPANT_CNTR
        {
            get
            {
                return this.pARTICIPANT_CNTRField;
            }
            set
            {
                this.pARTICIPANT_CNTRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string GSBER_REG
        {
            get
            {
                return this.gSBER_REGField;
            }
            set
            {
                this.gSBER_REGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string TYPE_CNTR
        {
            get
            {
                return this.tYPE_CNTRField;
            }
            set
            {
                this.tYPE_CNTRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string FINANCIAL_SIGN
        {
            get
            {
                return this.fINANCIAL_SIGNField;
            }
            set
            {
                this.fINANCIAL_SIGNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string ZSIGNDATE
        {
            get
            {
                return this.zSIGNDATEField;
            }
            set
            {
                this.zSIGNDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string ZSTARTDATE
        {
            get
            {
                return this.zSTARTDATEField;
            }
            set
            {
                this.zSTARTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string ZENDDATE
        {
            get
            {
                return this.zENDDATEField;
            }
            set
            {
                this.zENDDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string ZENDDATEPAY
        {
            get
            {
                return this.zENDDATEPAYField;
            }
            set
            {
                this.zENDDATEPAYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string ZFISTL
        {
            get
            {
                return this.zFISTLField;
            }
            set
            {
                this.zFISTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string GSBER_DCC
        {
            get
            {
                return this.gSBER_DCCField;
            }
            set
            {
                this.gSBER_DCCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string ZTERM
        {
            get
            {
                return this.zTERMField;
            }
            set
            {
                this.zTERMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string HBKID
        {
            get
            {
                return this.hBKIDField;
            }
            set
            {
                this.hBKIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string SIGNED_BY
        {
            get
            {
                return this.sIGNED_BYField;
            }
            set
            {
                this.sIGNED_BYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string SUM_NDS
        {
            get
            {
                return this.sUM_NDSField;
            }
            set
            {
                this.sUM_NDSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string ZCNTRSUMADD
        {
            get
            {
                return this.zCNTRSUMADDField;
            }
            set
            {
                this.zCNTRSUMADDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string ZCNTRNDSADD
        {
            get
            {
                return this.zCNTRNDSADDField;
            }
            set
            {
                this.zCNTRNDSADDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string NOT_SUM_CNTR
        {
            get
            {
                return this.nOT_SUM_CNTRField;
            }
            set
            {
                this.nOT_SUM_CNTRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string ZFIPOS
        {
            get
            {
                return this.zFIPOSField;
            }
            set
            {
                this.zFIPOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string ZBUSINESSPARTNER
        {
            get
            {
                return this.zBUSINESSPARTNERField;
            }
            set
            {
                this.zBUSINESSPARTNERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string ZPAYRCP_FP
        {
            get
            {
                return this.zPAYRCP_FPField;
            }
            set
            {
                this.zPAYRCP_FPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string ZFISTL_ITEM
        {
            get
            {
                return this.zFISTL_ITEMField;
            }
            set
            {
                this.zFISTL_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string DEPARTM_CONTROL
        {
            get
            {
                return this.dEPARTM_CONTROLField;
            }
            set
            {
                this.dEPARTM_CONTROLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string FINCODE
        {
            get
            {
                return this.fINCODEField;
            }
            set
            {
                this.fINCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string ZLSCH
        {
            get
            {
                return this.zLSCHField;
            }
            set
            {
                this.zLSCHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string ZSTARTDATE_FP
        {
            get
            {
                return this.zSTARTDATE_FPField;
            }
            set
            {
                this.zSTARTDATE_FPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string ZENDDATE_FP
        {
            get
            {
                return this.zENDDATE_FPField;
            }
            set
            {
                this.zENDDATE_FPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string OKPD2
        {
            get
            {
                return this.oKPD2Field;
            }
            set
            {
                this.oKPD2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string BANKGARANT
        {
            get
            {
                return this.bANKGARANTField;
            }
            set
            {
                this.bANKGARANTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string ZCOMMENTARY
        {
            get
            {
                return this.zCOMMENTARYField;
            }
            set
            {
                this.zCOMMENTARYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string TEMPLATE
        {
            get
            {
                return this.tEMPLATEField;
            }
            set
            {
                this.tEMPLATEField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportAsync
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inform.gazprom.ru/C/IUSPT2/eDocumentCardDraft", Order=0)]
        public EDocumentCardDraft.eDocumentCardDraft eDocumentCardDraft;
        
        public ExportAsync()
        {
        }
        
        public ExportAsync(EDocumentCardDraft.eDocumentCardDraft eDocumentCardDraft)
        {
            this.eDocumentCardDraft = eDocumentCardDraft;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface eDocumentCardDraftOutChannel : EDocumentCardDraft.eDocumentCardDraftOut, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class eDocumentCardDraftOutClient : System.ServiceModel.ClientBase<EDocumentCardDraft.eDocumentCardDraftOut>, EDocumentCardDraft.eDocumentCardDraftOut
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public eDocumentCardDraftOutClient(EndpointConfiguration endpointConfiguration) : 
                base(eDocumentCardDraftOutClient.GetBindingForEndpoint(endpointConfiguration), eDocumentCardDraftOutClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public eDocumentCardDraftOutClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(eDocumentCardDraftOutClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public eDocumentCardDraftOutClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(eDocumentCardDraftOutClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public eDocumentCardDraftOutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task EDocumentCardDraft.eDocumentCardDraftOut.ExportAsyncAsync(EDocumentCardDraft.ExportAsync request)
        {
            return base.Channel.ExportAsyncAsync(request);
        }
        
        public System.Threading.Tasks.Task ExportAsyncAsync(EDocumentCardDraft.eDocumentCardDraft eDocumentCardDraft)
        {
            EDocumentCardDraft.ExportAsync inValue = new EDocumentCardDraft.ExportAsync();
            inValue.eDocumentCardDraft = eDocumentCardDraft;
            return ((EDocumentCardDraft.eDocumentCardDraftOut)(this)).ExportAsyncAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                return new System.ServiceModel.EndpointAddress(@"http://dx1-db.codm.gazprom.loc:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=GTCH_DIRECTUM_D&receiverParty=&receiverService=&interface=eDocumentCardDraftOut&interfaceNamespace=http%3A%2F%2Finform.gazprom.ru%2FI%2FIUSPT2_SED%2FeDocumentCardDraft");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                return new System.ServiceModel.EndpointAddress(@"https://dx1-db.codm.gazprom.loc:50001/XISOAPAdapter/MessageServlet?senderParty=&senderService=GTCH_DIRECTUM_D&receiverParty=&receiverService=&interface=eDocumentCardDraftOut&interfaceNamespace=http%3A%2F%2Finform.gazprom.ru%2FI%2FIUSPT2_SED%2FeDocumentCardDraft");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTP_Port,
            
            HTTPS_Port,
        }
    }
}
